# Copyright 2023 DeepMind Technologies Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Class for evaluating programs proposed by the Sampler."""
import ast
from collections.abc import Sequence
import copy
from typing import Any
import textwrap
import re

import code_manipulation
import programs_database

# 【新增注入 1】：导入我们自定义的模块
from deduplicator import CodeDeduplicator
from sandbox import Sandbox as LocalSandbox  # 引入我们写好的多进程沙箱

evaluation_round = 0


class _FunctionLineVisitor(ast.NodeVisitor):
  """Visitor that finds the last line number of a function with a given name."""

  def __init__(self, target_function_name: str) -> None:
    self._target_function_name: str = target_function_name
    self._function_end_line: int | None = None

  def visit_FunctionDef(self, node: Any) -> None:  # pylint: disable=invalid-name
    """Collects the end line number of the target function."""
    if node.name == self._target_function_name:
      self._function_end_line = node.end_lineno
    self.generic_visit(node)

  @property
  def function_end_line(self) -> int:
    """Line number of the final line of function `target_function_name`."""
    assert self._function_end_line is not None  # Check internal correctness.
    return self._function_end_line


def _trim_function_body(generated_code: str) -> str:
    """提取生成的函数体，处理 Markdown、多余缩进及非法符号。"""
    if not generated_code:
        return ''

    # 1. 清理 LLM 可能返回的 Markdown 代码块
    code = generated_code
    if "```python" in code:
        code = re.split(r"```python", code)[1]
    if "```" in code:
        code = re.split(r"```", code)[0]

    lines = code.splitlines()
    body_lines = []
    found_def = False

    # 2. 提取函数体：寻找第一个 def 之后的所有内容
    for line in lines:
        if not line.strip():
            continue
        if re.match(r'^\s*def\s+\w+', line):
            found_def = True
            continue
        if found_def:
            body_lines.append(line)

    if not body_lines:
        body_lines = [l for l in lines if l.strip()]

    # 4. 使用 dedent 抹平最左侧空格，保留相对缩进
    raw_body = '\n'.join(body_lines)
    dedented_body = textwrap.dedent(raw_body)

    # 5. 【语法保护】：移除可能干扰 exec 的特殊符号
    clean_body = dedented_body.replace('`', '')

    # 6. 【关键修复】：为了迎合 DeepMind 底层模板，这里改为 2 个空格！
    final_body = textwrap.indent(clean_body, '  ')

    return final_body + '\n'


def _sample_to_program(
    generated_code: str,
    version_generated: int | None,
    template: code_manipulation.Program,
    function_to_evolve: str,
) -> tuple[code_manipulation.Function, str]:
  """Returns the compiled generated function and the full runnable program."""
  body = _trim_function_body(generated_code)
  if version_generated is not None:
    body = code_manipulation.rename_function_calls(
        body,
        f'{function_to_evolve}_v{version_generated}',
        function_to_evolve)

  program = copy.deepcopy(template)
  evolved_function = program.get_function(function_to_evolve)
  evolved_function.body = body
  return evolved_function, str(program)



def _calls_ancestor(program: str, function_to_evolve: str) -> bool:
  """Returns whether the generated function is calling an earlier version."""
  for name in code_manipulation.get_functions_called(program):
    # In `program` passed into this function the most recently generated
    # function has already been renamed to `function_to_evolve` (wihout the
    # suffix). Therefore any function call starting with `function_to_evolve_v`
    # is a call to an ancestor function.
    if name.startswith(f'{function_to_evolve}_v'):
      return True
  return False


# =========================================================================
# 替换原有的 Evaluator 类
# =========================================================================
class Evaluator:
  """Class that analyses functions generated by LLMs."""

  def __init__(
      self,
      database: programs_database.ProgramsDatabase,
      template: code_manipulation.Program,
      function_to_evolve: str,
      function_to_run: str,
      inputs: Sequence[Any],
      timeout_seconds: int = 30,
      deduplicator: CodeDeduplicator = None, # 【新增注入 2】：接收去重器实例
      bin_capacity: float = 150.0,  # 新增

  ):
    self.bin_capacity = bin_capacity
    self._database = database
    self._template = template
    self._function_to_evolve = function_to_evolve
    self._function_to_run = function_to_run
    self._inputs = inputs
    self._timeout_seconds = timeout_seconds
    
    # 【修改】：使用我们自定义的、带有多进程超时保护和装箱评测逻辑的 Sandbox
    # target_heuristic_name 指定了沙箱在模拟时需要调用的大模型生成的函数名
    self._sandbox = LocalSandbox(bin_capacity=bin_capacity, target_heuristic_name=function_to_evolve)

    self._deduplicator = deduplicator # 保存去重器实例

  def analyse(
      self,
      sample: str,
      island_id: int | None,
      version_generated: int | None,
  ) -> None:
    """Compiles the sample into a program and executes it on test inputs."""
    print("\n--- 🔍 [Debug] 开始评估新样本 ---")
    print(f"待评估代码片段:\n{sample}")

    # 1. 官方逻辑：将大模型生成的原始字符串解析为 FunSearch 内部的 Program AST 对象
    try:
        new_function, program = _sample_to_program(
            sample, version_generated, self._template, self._function_to_evolve)
        print("✅ [Debug] AST 语法树解析并拼装成功！")
    except Exception as e:
        print(f"[Evaluator Warning] 丢弃非法代码，AST 解析失败: {e}")
        # 如果 LLM 生成的代码存在严重语法错误，解析会失败，直接丢弃该样本
        return

    # =====================================================================
    # 【新增注入 3】：Integration 核心逻辑 - 检查去重缓存池
    # 对应论文中的: (1) Check if equivalent program exists (2) Reuse its score
    # =====================================================================
    if self._deduplicator:
        # ⚠️ 关键修正：使用拼装好的完整代码 str(program) 进行特征提取，并使用新版 API
        is_duplicate, cached_scores, hit_level = self._deduplicator.check_duplicate(str(program))

        if is_duplicate:
            print(f"[Evaluator] 缓存命中，层级: {hit_level}")  # 新增打印，便于观察
            print(f"[Cache Hit] 命中等效代码！跳过沙箱执行，直接为 Island {island_id} 复用分数。")
            # 查表成功！带着内部对象 `new_function` 注册到数据库，省下一次昂贵的沙箱评估时间
            self._database.register_program(new_function, island_id, cached_scores)
            return
    # =====================================================================

    
    # =====================================================================
    # 沙箱执行与评分环节
    # =====================================================================
    scores_per_test = {}
    print(f"⏳ [Debug] 开始沙箱测试，共 {len(self._inputs)} 个测试用例...")
    
    for i, current_input in enumerate(self._inputs):
        test_output, runs_ok = self._sandbox.run(
            program, self._function_to_evolve, current_input, self._timeout_seconds)
            
        # 防止生成的代码作弊（直接调用上一代函数的旧逻辑）
        is_cheating = _calls_ancestor(program, self._function_to_evolve)
        
        if runs_ok and not is_cheating and test_output is not None:
            if not isinstance(test_output, (int, float)):
                print(f"❌ [Debug] 测试用例 {i} 失败: 返回值类型错误，期望 int/float，实际拿到 {type(test_output)}")
                break
            scores_per_test[tuple(current_input)] = test_output
        else:
            # 💡 【核心排错点】：把到底因为什么失败打印出来
            print(f"❌ [Debug] 测试用例 {i} 失败！")
            print(f"    -> runs_ok 状态: {runs_ok}")
            print(f"    -> test_output 结果: {test_output}")
            print(f"    -> 是否触发防作弊拦截: {is_cheating}")
            break

    # =====================================================================
    # 结果注册环节
    # =====================================================================
    if len(scores_per_test) == len(self._inputs):
        avg_score = sum(scores_per_test.values()) / len(scores_per_test)
        print(f"✅ [Debug] 所有测试用例通过！平均得分: {avg_score:.2f}")
        # 如果所有测试用例都成功跑完并得分，注册到 FunSearch 数据库
        self._database.register_program(new_function, island_id, scores_per_test)
        # 注册成功后
        global evaluation_round
        evaluation_round += 1
        print(f"✅ 第 {evaluation_round} 轮有效评估完成！")
        
        # 对应论文中的: (3) If no, evaluate and add to pool
        if self._deduplicator:
            # ⚠️ 关键修正：使用新版 API register，并保存完整代码的特征
            self._deduplicator.register(str(program), scores_per_test)
            
        print("✅ [Debug] 成功存入数据库！")
    else:
        print(f"❌ [Debug] 致命：成功用例数 ({len(scores_per_test)}) 不等于总用例数 ({len(self._inputs)})，程序被丢弃！")
        
    print("--- 🔍 [Debug] 评估流程结束 ---\n")